In [1]:
import pandas as pd 
from data_capture import FromYF
import inputs
from pypfopt.expected_returns import returns_from_prices
from core.prediction import regressed_expected_returns, relative_shortfall_risk

In [2]:
watchlist_df = pd.read_excel(inputs.WATCHLIST_PATH,index_col=0)
watchlist = watchlist_df.index.tolist()
watchlist.append(inputs.MARKET)

price_df = FromYF.get_prices(watchlist,period=inputs.PERIOD,interval=inputs.INTERVAL)

returns_df = returns_from_prices(price_df,log_returns=inputs.IS_CONTINOUSLY_COMPOUNDED)

returns_df

[*********************100%***********************]  5 of 5 completed

                AAPL      AMZN     GOOGL      TSLA      ^RUA
Date
2020-07-28 -0.016427 -0.017963 -0.016856 -0.040991 -0.007094
2020-07-29  0.019168  0.011065  0.013208  0.015320  0.013811
2020-07-30  0.012100  0.006049  0.009754 -0.007751 -0.003390
2020-07-31  0.104689  0.036961 -0.032775 -0.038138  0.005645
2020-08-03  0.025198 -0.016681 -0.003488  0.037910  0.008723
...              ...       ...       ...       ...       ...
2022-07-20  0.013510  0.038575  0.000791  0.008023  0.007983
2022-07-21  0.015094  0.015150  0.003863  0.097805  0.009424
2022-07-22 -0.008111 -0.017732 -0.056323  0.001975 -0.010572
2022-07-25 -0.007398 -0.010456 -0.003614 -0.013995  0.001458
2022-07-26 -0.008826 -0.052254 -0.023161 -0.035664 -0.012013

[501 rows x 5 columns]

In [3]:
E_df = regressed_expected_returns(returns_df,inputs.MARKET)

E_df

          predict  predict_lower  predict_upper
tickers
AAPL     0.001166      -0.025620       0.027953
AMZN    -0.000308      -0.031991       0.031376
GOOGL    0.000811      -0.023235       0.024856
TSLA     0.002694      -0.063989       0.069376
^RUA     0.000426       0.000426       0.000426

In [4]:
shortfall_risk_df = relative_shortfall_risk(returns_df,inputs.SHORTFALL_PERIODS)

shortfall_risk_df

               AAPL      AMZN     GOOGL      TSLA      ^RUA
p(<AAPL)   0.000000  0.642323  0.536363  0.422524  0.593295
p(<AMZN)   0.357677  0.000000  0.390366  0.357202  0.422360
p(<GOOGL)  0.463637  0.609634  0.000000  0.410863  0.554606
p(<TSLA)   0.577476  0.642798  0.589137  0.000000  0.611312
p(<^RUA)   0.406705  0.577640  0.445394  0.388688  0.000000