In [1]:
import pandas as pd
from pypfopt.expected_returns import returns_from_prices
from data_capture import FromYF
import inputs
from core.regression import regression

In [2]:
watchlist_df = pd.read_excel(inputs.WATCHLIST_PATH,index_col=0)
watchlist = watchlist_df.index.tolist()
watchlist.append(inputs.MARKET)

price_df = FromYF.get_prices(watchlist,period=inputs.PERIOD,interval=inputs.INTERVAL)

returns_df = returns_from_prices(price_df,log_returns=inputs.IS_CONTINOUSLY_COMPOUNDED)

returns_df

[*********************100%***********************]  5 of 5 completed

                AAPL      AMZN     GOOGL      TSLA      ^RUA
Date
2020-07-28 -0.016428 -0.017963 -0.016856 -0.040991 -0.007094
2020-07-29  0.019168  0.011065  0.013208  0.015320  0.013811
2020-07-30  0.012100  0.006049  0.009754 -0.007751 -0.003390
2020-07-31  0.104689  0.036961 -0.032775 -0.038138  0.005645
2020-08-03  0.025198 -0.016681 -0.003488  0.037910  0.008723
...              ...       ...       ...       ...       ...
2022-07-20  0.013510  0.038575  0.000791  0.008023  0.007983
2022-07-21  0.015094  0.015150  0.003863  0.097805  0.009424
2022-07-22 -0.008111 -0.017732 -0.056323  0.001975 -0.010572
2022-07-25 -0.007398 -0.010456 -0.003614 -0.013995  0.001458
2022-07-26 -0.008826 -0.052254 -0.023161 -0.035664 -0.012013

[501 rows x 5 columns]

In [3]:
regression_df = regression(returns_df,inputs.MARKET)

regression_df

,alpha,betav,alpha_t_stat,beta_t_stat,skewness,kurtoses,betaub,betalb,alphalb,alphaub,epsilon
tickers,,,,,,,,,,,
AAPL,6.150235e-04,1.293900,1.010031,2.460311e+01,0.860,9.316,1.190573,1.190573,-5.813309e-04,1.811378e-03,0.335098
AMZN,-9.045754e-04,1.401185,-1.255946,2.252517e+01,0.679,13.416,1.278968,1.278968,-2.319641e-03,5.104904e-04,0.362883
GOOGL,2.817415e-04,1.241706,0.515439,2.630215e+01,0.940,8.916,1.148952,1.148952,-7.921902e-04,1.355673e-03,0.321581
TSLA,1.833809e-03,2.017762,1.209763,1.541213e+01,0.439,5.806,1.760539,1.760539,-1.144409e-03,4.812028e-03,0.522566
^RUA,-6.810145e-19,1.000000,-25.455884,4.327912e+17,-0.127,1.119,1.000000,1.000000,-7.335764e-19,-6.284526e-19,0.258983